### ISSUE TITLE
create() doesn't set user member

### ISSUE THREAD

**Issue by kormat** [opensourcerouting/c-capnproto#10]
I could be mis-reading this, but it looks like https://github.com/opensourcerouting/c-capnproto/blob/master/lib/capn-malloc.c#L38 should instead be:
```
s->user = u;
```

**Comment by eqvinox** [comment]
Nope, it's correct - `s->user` is the "user pointer for the memory management routines".  The built-in routines use it to know what to call `free()` on; if you use other functions to allocate/free memory you could use it differently.

I do agree it's rather confusing & misleading though, if you want to submit a patch to improve the names or documentation or comments...
