### ISSUE TITLE
capnpc-c exit with code 2 if there is an unused struct in included file

### ISSUE THREAD

**Issue by assaf758** [opensourcerouting/c-capnproto#11]
$ cat infra.capnp 
@0xab01f6ae1ef59a57;
struct S1 {
    s1 @0 :Int64;
}
struct S2 {
    s2 @0 :Int64;
}

$ cat msg.capnp   
@0xed2b3b98b3eb515b;
using import "/infra.capnp".S1;
struct M {
    m1  @0: S1;
}

$ capnp -I ~/ws/capn compile -o /home/assafb/ws/capn/capnpc-c:/home/assafb/ws/capn/ ~/ws/capn/msg.capnp
cant find node with id 0x85f0eda94e40ad1a
/home/assafb/iguazio/workspace/engine/zeek/build/vendor/c-capnproto/capnpc-c: plugin failed: exit code 2

**Comment by eqvinox** [comment]
Thanks for the report - fixed by 52ca907 (please check/confirm!)

**Comment by eqvinox** [comment]
confirmed fixed - closing
