### ISSUE TITLE
Show in docs the Example Usage in C

### ISSUE THREAD

**Issue by dariomt** [opensourcerouting/c-capnproto#13]
It would be great if you could show in the docs how the Example Usage in https://capnproto.org/cxx.html translates into C using this plugin.

**Comment by fluffysquirrels** [comment]
Yes, I really like this idea. I'm getting an example working in my own project and then will probably copy it to this project's README.md.

**Comment by fluffysquirrels** [comment]
I have a simple example working in my project now as a unit test. I'm thinking of implementing something similar in c-capnproto and referencing it from the repository README.md. Then you can be sure the example works as it'll be checked by Travis on every commit. Any thoughts on this?

**Comment by eqvinox** [comment]
Not sure how assigning things works, apparently I can only assign to people in the @opensourcerouting org...

Nonetheless I'll be happy to merge documentation!

**Comment by eqvinox** [comment]
P.S.: in quagga-capnproto (which is outdated; working on a new version), it's used in these files:

https://github.com/opensourcerouting/quagga-capnproto/blob/capnproto/lib/qzc.c
https://github.com/opensourcerouting/quagga-capnproto/blob/capnproto/lib/qzc.h
https://github.com/opensourcerouting/quagga-capnproto/blob/capnproto/lib/qzc.capnp
and the build system setup is in
https://github.com/opensourcerouting/quagga-capnproto/blob/capnproto/lib/Makefile.am

**Comment by fluffysquirrels** [comment]
@eqvinox, great, thanks! I think those are the files I used to get my own example working.

**Comment by eqvinox** [comment]
good to see you found it in the forest of code ;)
btw, to clarify - the cap'n proto usage is not outdated; it's the version of our application which is outdated.

**Comment by maxux** [comment]
Here is what I could find myself from what I read below and reading original source code. Thanks for links btw. I hope this could help someones:

# Schema Sample
```
struct Inode {
    name    @0: Text;
    size    @1: UInt64;
    [...]
}

struct Dir {
    name     @0: Text;
    contents @1: List(Inode);
    modificationTime @2: UInt64;
    [...]
}
```

# Read the struct
Loading a payload message is done via `capn_init_mem`.
- `data` is a `char *` containing the payload
- `length` is a size_t (length of the payload)
```c
    struct capn ctx;
    if(capn_init_mem(&ctx, data, length, 0))
        fprintf(stderr, "[-] capnp: init error\n"); 
```

We assume the payload contains a `Dir` object, let's load it
```c
    Dir_ptr dirp;
    struct Dir dir;
    dirp.p = capn_getp(capn_root(&ctx), 0, 1);
    read_Dir(&dir, dirp);

    // Now on the dir struct, we can access members directly
    printf("Name: %s\n", dir.name.str);
    printf("Size: %lu\n", dir.size);
```

To iterate over a List, just use `getp` with index id as argument
```c
    Inode_ptr inodep;
    struct Inode inode;

    for(int i = 0; i < capn_len(dir.contents); i++) {
        inodep.p = capn_getp(dir.contents.p, i, 1);

        read_Inode(&inode, inodep);
        printf("Name: %s\n", inode.name.str);
        printf("Size: %lu\n", inode.size);
    }
```

Cleaning memory at the end.
```c
    capn_free(&ctx);
```

**Comment by fluffysquirrels** [comment]
@maxux Thanks for your notes! I had figured out something similar in my code. The [PR](https://github.com/opensourcerouting/c-capnproto/pull/16) is fairly complete now, I think. I was just waiting on @eqvinox to OK the compiler changes before committing.

**Comment by fluffysquirrels** [comment]
[PR 16](https://github.com/opensourcerouting/c-capnproto/pull/16) is merged now. I think this issue is now resolved and I will close it. I'm happy to take suggestions for new documentation in this issue or another.
