### ISSUE TITLE
capn_getv returns -1

### ISSUE THREAD

**Issue by xvuko** [opensourcerouting/c-capnproto#20]
I have problem with reading build-in list types. This code simply creates new Message structure, calls capn_setv, writes  message to  capn segment and reads it. After this operations calling capn_getv on body fails. 

d.capnp:
```
@0xec7cea5be31ae639;

struct Message {
    body @0 :List(UInt8);
}
```

d.c:
```
#include <capnp_c.h>
#include <string.h>

#include "d.capnp.h"

struct msg_capn_t {
    uint8_t segment_bytes[128];  
    struct capn_segment s; 
    struct capn c;
    struct Message msg;
    Message_ptr ptr;
};

int main(void){
    struct msg_capn_t ms;
    memset(&ms, 0, sizeof(ms));
    ms.s.data = (char*)ms.segment_bytes;
    ms.s.cap = sizeof(ms.segment_bytes);
    capn_append_segment(&ms.c, &ms.s);
    capn_root(&ms.c);
    
    // Begin capnp root
    ms.ptr = new_Message(&ms.s);
    capn_setp(capn_root(&ms.c), 0, ms.ptr.p);
    
    {   // Begin capnp child
        uint8_t buffer[2] = {99, 76};
        ms.msg.body = capn_new_list8(&ms.s, 2);
        capn_setv8(ms.msg.body, 0, buffer, 2);
    }
    write_Message(&ms.msg, ms.ptr);
    read_Message(&ms.msg, ms.ptr);
    {   // Begin capnp child
        uint8_t buffer[2] = {0, 0};
        int c = capn_getv8(ms.msg.body,0, buffer, 2);
        if (c == 2){
            printf("success\n");
            return 0;
        } else {
            printf("fail capn_getv returned %d\n",c);
            return 1;
        }
    }
}
```

I have found one solution - manually changing generated file d.capnp.c from:
```
void read_Message(struct Message *s, Message_ptr p) {
	capn_resolve(&p.p);
	s->body.p = capn_getp(p.p, 0, 0);
}
```
to
```
void read_Message(struct Message *s, Message_ptr p) {
	capn_resolve(&p.p);
	s->body.p = capn_getp(p.p, 0, 1);
}
```
This can also be changed in c-capnproto/compiler/capnpc-c.c:604
`str_addf(func, "%s = capn_getp(%s, %d, 1);\n", pvar, ptr, f->f.slot.offset);`
but I am not sure if it is correct solution, or bug is somewhere else (for example in my code).

**Comment by xvuko** [comment]
OK, I have some other solutions:
1. manually calling capn_resolve on list pointer before using capn_getv - it works without changes to c-capnproto, but it adds unnecessary function call to user code
2.  adding capn_resolve into capn_getv body - it seems like best solution and is consistent with read_X functions generated by capnp

**Comment by eqvinox** [comment]
It's probably an oversight, I guess there should have been a `capn_resolve` call in `capn_getv`.

**Comment by eqvinox** [comment]
Can you check that the change in PR #21 fixes this?

**Comment by xvuko** [comment]
Yes it does.
