### ISSUE TITLE
Really Need Documentation

### ISSUE THREAD

**Issue by slayercat** [opensourcerouting/c-capnproto#7]
Document Required. digging code makes me crezy.

**Comment by eqvinox** [comment]
Sorry, I'm neither the original author (which means I also need to dig the code...) and I don't have extra time to write documentation.  If you send a patch with docs, I'll be happy to merge them...

**Comment by fluffysquirrels** [comment]
I've just closed [issue 13](https://github.com/opensourcerouting/c-capnproto/issues/13), which I think helps with this. Are there any specific suggestions for extra documentation you'd like to see? E.g. further examples or per-function documentation?

**Comment by eqvinox** [comment]
closing, the examples added by @fluffysquirrels should cover this (Thanks again!)
